### ISSUE TITLE
Support for loading fp8 checkpoint

### ISSUE THREAD

**Issue by wenscarl** [google/praxis#68]
There is a use_fp flag for the offline_quantize tool to quantize the weight in fp8 but still has to be stored in int8(https://github.com/google/praxis/blob/3f4cbb4bcda366db7b018695fbe2d40868d19e3e/praxis/layers/quantization/operations.py#L776).  If that is always the case, is there any example showcasing how to load a checkpoint in int8 but interpret as fp8? @jianlijianli

**Comment by jianlijianli** [comment]
Hi wenscarl, could you please take a look [here](https://github.com/google/praxis/blob/3f4cbb4bcda366db7b018695fbe2d40868d19e3e/praxis/layers/quantization/quantizer.py#L267-L272)? Since we did a bitcast during save, we need to use a bitcast during serving.

**Comment by wenscarl** [comment]
Thanks. If the checkpoint is generated by `use_fp=True`, but at [weights setup](https://github.com/google/praxis/blob/3f4cbb4bcda366db7b018695fbe2d40868d19e3e/praxis/layers/quantization/quantizer.py#L94), the dtype is still int8. Is there something I am missing?  I only see one example [here](https://github.com/google/saxml/blob/main/saxml/server/pax/quantization.py#L20-L32).
For fp8 inference, we only set 4 layers in transformer, `ffn1`, `ffn2`, `combined_qkv` and `post` to be fp8 and they do not go through `quantized_einsum`.  Could you provide some design advice? Thanks!

**Comment by jianlijianli** [comment]
Hi wenscarl, we can enable running the fp8 model (stored as int8) by setting `dtype=jnp.float8_e4m3fn` in the [for_transformer()](https://github.com/google/saxml/blob/main/saxml/server/pax/quantization.py#L57) decorator.

There are several architecture variations but for a basic transformer with MHA, `ffn1`, `ffn2`, `combined_qkv` and `post` are the weights that `for_transformer()` quantizes (i.e. that API would have trouble if you want to quantize ffn1, ffn2 and post, but not combined_qkv). So setting the `dtype=jnp.float8_e4m3fn` might just work for your use case.

Could you please elaborate on "they do not go through quantized_einsum"?

**Comment by wenscarl** [comment]
>Could you please elaborate on "they do not go through quantized_einsum"?
For fp8 training/inference, those layers are replaced by [Fp8EinsumOp](https://github.com/google/flax/blob/main/flax/linen/fp8_ops.py). See the USE_FP8 option in PAXML [here](https://github.com/google/paxml/blob/35bc7401ae00d7c40a764f5e1d341813ac3dadfc/paxml/tasks/lm/model_params.py#L674C1-L683C8).
I tried `dtype=jnp.float8_e4m3fn` with the decorator, it complains about:
```
Traceback (most recent call last):
  File "/model-server-bin/server.runfiles/__main__/saxml/server/server.py", line 144, in _load_static_model
    stub.Load(req)
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 1181, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 1006, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Cannot intersect index domain {  } with index domain { [0, 3), [0, 8), [0, 128) }: Ranks do not match [source locations='tensorstore/index_space/index_transform.cc:507']"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:10001 {grpc_message:"Cannot intersect index domain {  } with index domain { [0, 3), [0, 8), [0, 128) }: Ranks do not match [source locations=\'tensorstore/index_space/index_transform.cc:507\']", grpc_status:3, created_time:"2024-05-23T15:16:30.907321245+00:00"}"

The way I used offline_quantize.py is 
```
python saxml/tools/offline_quantize.py --input_dir /tmp/ckpts/fp8_train//checkpoints/checkpoint_00000000/state/ --output_dir /output/patch/checkoutpoint_0000000/state --quantization_configs "gptj" --use_fp True
where the input is a f32 checkpoint.

**Comment by wenscarl** [comment]
if the gptj config is set to 
```
  configs = {
      'ff_layer.ffn_layer1.linear.w': ([1], factor, 0, -1),
      'ff_layer.ffn_layer2.linear.w': ([1], factor, 0, -1),
      'self_attention.combined_qkv.w': ([0, 2, 3], factor, 0, -1),
      'self_attention.post.w': ([1, 2], factor, 0, -1),
  }
  ```
  the checkpoint loading is able to make through. But will hit error, 
```
pybind11_abseil.status.StatusNotOk: OUT_OF_RANGE: Invalid id: 11011
         [[{{function_node map_1_while_body_459}}{{node SentenceTokenizer/SentencepieceDetokenizeOp}}]]
E0523 21:46:05.865277 140622177190336 server.py:146] Exception during loading: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Loading error: OUT_OF_RANGE: Invalid id: 11011
         [[{{function_node map_1_while_body_459}}{{node SentenceTokenizer/SentencepieceDetokenizeOp}}]]"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:10001 {created_time:"2024-05-23T21:46:05.864696671+00:00", grpc_status:13, grpc_message:"Loading error: OUT_OF_RANGE: Invalid id: 11011\n\t [[{{function_node map_1_while_body_459}}{{node SentenceTokenizer/SentencepieceDetokenizeOp}}]]"}"
>
```
Is there any example showcasing how to run offline_quantize tool to generated a quantized checkpoint and then loaded by saxml for inference?

**Comment by wenscarl** [comment]
>Did you run into any issues with float?
I can run with float without any issue by: 1. not using `for_transformer` decorator, 2. directly loading in a float checkpoint rather than pre-quantized checkpoint.

**Comment by wenscarl** [comment]
Update:
Running inference with weight in fp8 is experimentally feasible with [change](https://github.com/wenscarl/praxis/commit/e5a8d0b75ef10678ef816abb6b4ed5a5dd3c8ddc) except that the scale is dummy. 
Only feed_forward layers are quantized with `linear_only=True`.
For fp8 matmul, only per-tensor-scale is supported now by cublasLt. The gptj config is set as
```
  configs = {
      'ff_layer.ffn_layer1.linear.w': ([0, 1], factor, 0, -1),
      'ff_layer.ffn_layer2.linear.w': ([0,1], factor, 0, -1),
  }
```
such that the resulting `w_quantized_scale` is a scalar of shape `[]`. But [here](https://github.com/google/praxis/blob/main/praxis/layers/quantization/linears.py#L109) specifies that the `scale_shape` being a vector.  But even forcing `scale_shape` to be a scalar, there will be error:
```
I0528 21:12:05.819829 140044237002304 checkpointer.py:164] Restoring item from /tmp/ckpts/mybucket/fp8/checkpoint_00000000.
E0528 21:12:05.862007 140044237002304 model_service_base.py:1557] Invalid load request. model_key: /sax/test/lm2b, model_path: saxml.server.pax.lm.params.lm_cloud.LmCloudSpmd2B, error: Cannot intersect index domain {  } with index domain { [0, 1) }: Ranks do not match [source locations='tensorstore/index_space/index_transform.cc:507']
Traceback (most recent call last):
  File "/model-server-bin/server.runfiles/__main__/saxml/server/model_service_base.py", line 1547, in _run_primary_worker_loop
    self._load_model(
  File "/model-server-bin/server.runfiles/__main__/saxml/server/model_service_base.py", line 1368, in _load_model
    self._loaded_models.load(
  File "/model-server-bin/server.runfiles/__main__/saxml/server/model_service_base.py", line 511, in load
    loaded = params.load(key, ckpt_path, self._primary_process_id, prng_key)
  File "/model-server-bin/server.runfiles/__main__/saxml/server/pax/servable_model_params.py", line 154, in load
    model.load(checkpoint_path, jax.random.PRNGKey(prng_key))
  File "/model-server-bin/server.runfiles/__main__/saxml/server/pax/servable_model.py", line 410, in load
    model, model_state = self.load_state(checkpoint_path, init_key, precompile)
  File "/model-server-bin/server.runfiles/__main__/saxml/server/pax/servable_model.py", line 506, in load_state
    partitioned_train_state = CKPT_MODULE.restore_checkpoint(
  File "/opt/paxml/paxml/checkpoints.py", line 246, in restore_checkpoint
    output = checkpoint_manager.restore(
  File "/opt/paxml/paxml/checkpoint_managers.py", line 605, in restore
    restored = self._manager.restore(
  File "/usr/local/lib/python3.10/dist-packages/orbax/checkpoint/checkpoint_manager.py", line 867, in restore
    restored = self._checkpointer.restore(restore_directory, args=args)
  File "/usr/local/lib/python3.10/dist-packages/orbax/checkpoint/checkpointer.py", line 166, in restore
    restored = self._handler.restore(directory, args=ckpt_args)
  File "/usr/local/lib/python3.10/dist-packages/orbax/checkpoint/composite_checkpoint_handler.py", line 459, in restore
    restored[item_name] = handler.restore(
  File "/usr/local/lib/python3.10/dist-packages/orbax/checkpoint/composite_checkpoint_handler.py", line 137, in restore
    return self._handler.restore(directory, *args.args, **args.kwargs)
  File "/opt/paxml/paxml/checkpoints.py", line 587, in restore
    restored_train_state = super().restore(
  File "/usr/local/lib/python3.10/dist-packages/orbax/checkpoint/pytree_checkpoint_handler.py", line 1073, in restore
    restored_item = asyncio.run(
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/paxml/paxml/checkpoints.py", line 511, in _maybe_deserialize
    return await super()._maybe_deserialize(
  File "/usr/local/lib/python3.10/dist-packages/orbax/checkpoint/pytree_checkpoint_handler.py", line 903, in _maybe_deserialize
    deserialized_batches += await asyncio.gather(*deserialized_batches_ops)
  File "/usr/local/lib/python3.10/dist-packages/orbax/checkpoint/type_handlers.py", line 1531, in deserialize
    ret = await asyncio.gather(*deserialize_ops)
  File "/opt/jax/jax/experimental/array_serialization/serialization.py", line 311, in async_deserialize
    return await create_async_array_from_callback(tuple(shape), in_sharding, cb)
  File "/opt/jax/jax/experimental/array_serialization/serialization.py", line 76, in create_async_array_from_callback
    dbs = await asyncio.gather(*future_arrays)
  File "/opt/jax/jax/experimental/array_serialization/serialization.py", line 281, in cb
    restricted_domain = t.domain.intersect(requested_domain)
ValueError: Cannot intersect index domain {  } with index domain { [0, 1) }: Ranks do not match [source locations='tensorstore/index_space/index_transform.cc:507']
E0528 21:12:05.864998 140067501011392 server.py:146] Exception during loading: <_InactiveRpcError of RPC that terminated with:
```
Is there an example showcasing how to do per-tensor-scaling properly?

**Comment by wenscarl** [comment]
@jianlijianli for viz.

**Comment by jianlijianli** [comment]
Hi wenscarl, sorry for the delay. Pax defaults everything to per-channel quantization so there is no API for per-tensor quantization, but it should be easy to hack a bit locally to run per-tensor. I think all we need is to set scale dims to [1] [here](https://github.com/google/praxis/blob/main/praxis/layers/quantization/quantizer.py#L138C11-L138C22).

The [runtime](https://github.com/google/praxis/blob/main/praxis/layers/quantization/operations.py#L645) should be able to handle both per-tensor and per-channel scale, thanks to the broadcast behavior of multiply.

**Comment by wenscarl** [comment]
Hi @jianlijianli, some updates.
I am able to run fp8 inference with the following experimental praxis and saxml PRs.
https://github.com/google/saxml/pull/27
https://github.com/google/praxis/pull/72
Due to the cublasLt fp8 matmul limitations, the quantization has to be weight-and-activation, per-tensor, symmetric. 
1. The static activation quantization is not supported yet, [here](https://github.com/google/praxis/blob/e27bd4f112cff1a0c1e564dc03283f241bbb85a4/praxis/layers/quantization/linears.py#L319-L322). How should one properly provide support for it in the future?
2. The comment [here ](https://github.com/google/praxis/blob/main/praxis/layers/quantization/quantize.py#L286)is a bit confusing. Doesn't it support the activation quantization in the attention layer?

**Comment by jianlijianli** [comment]
Hi wenscarl, apologies for the delay and really glad you had fp8 working now.

The static activation quantization is less useful so we didn't support it yet. But it should not be too hard to support it. How do you plan to do static activation? The static activation scale are collected from QAT training or calibration?

The comment in https://github.com/google/praxis/blob/main/praxis/layers/quantization/quantize.py#L286 is a bit confusing. The entire quantize.py is rewriting checkpoints so from that point of view it's always weight-only, for both ffw and attention.
